import React from 'react';
import { FileText, Printer, Download, Sparkles, CheckCircle2, AlertTriangle, ShieldCheck } from 'lucide-react';

export const ReportsPage: React.FC = () => {
  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="space-y-6 pb-12">
      
      {/* Title & Action */}
      <div className="flex flex-wrap items-center justify-between gap-4 no-print">
        <div>
          <h1 className="text-2xl font-extrabold text-white flex items-center gap-2">
            <FileText className="w-6 h-6 text-indigo-400" />
            <span>Executive HR Summary Report</span>
          </h1>
          <p className="text-xs text-slate-400 mt-1">
            Print-friendly debrief report summarizing drive metrics, friction scores, and AI recommendations.
          </p>
        </div>

        <button
          onClick={handlePrint}
          className="gradient-btn px-4 py-2 rounded-xl text-xs font-bold flex items-center gap-2"
        >
          <Printer className="w-4 h-4" />
          <span>Print / Export PDF Report</span>
        </button>
      </div>

      {/* Printable Report Document Container */}
      <div className="glass-card p-8 space-y-6 max-w-4xl mx-auto print:shadow-none print:border-none text-slate-100">
        
        {/* Report Header */}
        <div className="flex items-center justify-between border-b border-slate-800 pb-6">
          <div>
            <div className="flex items-center gap-2">
              <span className="font-extrabold text-2xl tracking-tight text-white">HirePulse AI</span>
              <span className="text-xs px-2 py-0.5 rounded bg-indigo-500/20 text-indigo-300 font-bold">
                HR Intelligence Report
              </span>
            </div>
            <h2 className="text-base font-bold text-slate-300 mt-1">Software Engineer Walk-In Drive 2026</h2>
            <p className="text-xs text-slate-400">Date: August 27, 2026 • Location: Tech Hub Floor 4 • Job Role: Senior Full-Stack Engineer</p>
          </div>

          <div className="text-right text-xs text-slate-400">
            <div>Drive ID: <strong>DRIVE-2026-001</strong></div>
            <div>Generated by: <strong>HirePulse AI Engine</strong></div>
          </div>
        </div>

        {/* Executive Summary Section */}
        <div className="space-y-3">
          <h3 className="font-extrabold text-white text-sm uppercase tracking-wider">1. Executive Overview</h3>
          <p className="text-xs text-slate-300 leading-relaxed bg-slate-950 p-4 rounded-xl border border-slate-800">
            The Walk-In Recruitment Drive registered <strong>300 total candidates</strong> with <strong>42 selected hires</strong> (14.0% selection rate). Technical Round was identified as the primary operational bottleneck, generating an average waiting time of <strong>78.5 minutes</strong> and a Candidate Friction Score of <strong>78/100 (Critical)</strong>. 48 candidates silently abandoned the drive at this stage.
          </p>
        </div>

        {/* KPI Grid Summary */}
        <div className="grid grid-cols-4 gap-3 text-xs text-center">
          <div className="bg-slate-950 p-3 rounded-lg border border-slate-800">
            <span className="text-slate-400 block text-[10px]">Candidates Analyzed</span>
            <strong className="text-white text-lg font-black">300</strong>
          </div>
          <div className="bg-slate-950 p-3 rounded-lg border border-slate-800">
            <span className="text-slate-400 block text-[10px]">Hired Candidates</span>
            <strong className="text-emerald-400 text-lg font-black">42</strong>
          </div>
          <div className="bg-slate-950 p-3 rounded-lg border border-slate-800">
            <span className="text-slate-400 block text-[10px]">Total Dropouts</span>
            <strong className="text-rose-400 text-lg font-black">72</strong>
          </div>
          <div className="bg-slate-950 p-3 rounded-lg border border-slate-800">
            <span className="text-slate-400 block text-[10px]">Highest Friction</span>
            <strong className="text-amber-400 text-lg font-black">78 / 100</strong>
          </div>
        </div>

        {/* Stage Metrics Table */}
        <div className="space-y-3">
          <h3 className="font-extrabold text-white text-sm uppercase tracking-wider">2. Stage Performance Breakdown</h3>
          <table className="w-full text-left text-xs border border-slate-800 rounded-lg overflow-hidden">
            <thead className="bg-slate-950 text-slate-400 font-bold uppercase text-[10px]">
              <tr>
                <th className="py-2.5 px-3">Stage</th>
                <th className="py-2.5 px-3">Entered</th>
                <th className="py-2.5 px-3">Completed</th>
                <th className="py-2.5 px-3">Avg Wait</th>
                <th className="py-2.5 px-3">Friction Score</th>
                <th className="py-2.5 px-3">Bottleneck Status</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800 text-slate-300">
              <tr><td className="py-2 px-3 font-bold text-white">Registration</td><td className="py-2 px-3">300</td><td className="py-2 px-3">295</td><td className="py-2 px-3">12.5m</td><td className="py-2 px-3">18/100</td><td className="py-2 px-3 text-emerald-400">Low friction</td></tr>
              <tr><td className="py-2 px-3 font-bold text-white">HR Screening</td><td className="py-2 px-3">295</td><td className="py-2 px-3">260</td><td className="py-2 px-3">28.0m</td><td className="py-2 px-3">32/100</td><td className="py-2 px-3 text-sky-400">Medium friction</td></tr>
              <tr className="bg-rose-950/20"><td className="py-2 px-3 font-bold text-rose-300">Technical Round</td><td className="py-2 px-3">248</td><td className="py-2 px-3">160</td><td className="py-2 px-3 font-bold text-rose-400">78.5m</td><td className="py-2 px-3 font-bold text-rose-400">78/100</td><td className="py-2 px-3 font-bold text-rose-400">Critical bottleneck</td></tr>
              <tr><td className="py-2 px-3 font-bold text-white">Managerial Round</td><td className="py-2 px-3">112</td><td className="py-2 px-3">78</td><td className="py-2 px-3">35.0m</td><td className="py-2 px-3">41/100</td><td className="py-2 px-3 text-amber-400">Medium friction</td></tr>
              <tr><td className="py-2 px-3 font-bold text-white">Final Decision</td><td className="py-2 px-3">72</td><td className="py-2 px-3">42</td><td className="py-2 px-3">15.0m</td><td className="py-2 px-3">14/100</td><td className="py-2 px-3 text-emerald-400">Low friction</td></tr>
            </tbody>
          </table>
        </div>

        {/* AI Action Recommendations Summary */}
        <div className="space-y-3">
          <h3 className="font-extrabold text-white text-sm uppercase tracking-wider">3. AI Recommendations & Projections</h3>
          <div className="bg-indigo-950/40 p-4 rounded-xl border border-indigo-500/30 text-xs space-y-2">
            <div className="font-bold text-indigo-300 text-sm">Critical Recommendation: Add 1 Technical Interviewer Panel</div>
            <p className="text-slate-200">
              Deploying +1 technical interviewer during 10 AM - 2 PM peak hours is projected to reduce Technical Round wait time from <strong>78.5m → 48.0m (-36%)</strong> and decrease drive dropouts from <strong>24.5% → 16.0% (-35%)</strong>.
            </p>
          </div>
        </div>

      </div>

    </div>
  );
};
